package com.zyhao.openec.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Model class of 信息模板.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity(name="info_templete")
public class InfoTemplete implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue
	private Long id;

	/** 名称. */
	private String name;

	/** 图片路径. */
	private String picturePath;

	/** 类型1-平台，2-商店. */
	private String type;

	/** 创建时间. */
	private Long createdAt;

	/** 模板存放路径. */
	private String filePath;

	/**
	 * Constructor.
	 */
	public InfoTemplete() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 图片路径.
	 * 
	 * @param picturePath
	 *            图片路径
	 */
	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	/**
	 * Get the 图片路径.
	 * 
	 * @return 图片路径
	 */
	public String getPicturePath() {
		return this.picturePath;
	}

	/**
	 * Set the 类型1-平台，2-商店.
	 * 
	 * @param type
	 *            类型1-平台，2-商店
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Get the 类型1-平台，2-商店.
	 * 
	 * @return 类型1-平台，2-商店
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createdAt
	 *            创建时间
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Long getCreatedAt() {
		return this.createdAt;
	}

	/**
	 * Set the 模板存放路径.
	 * 
	 * @param filePath
	 *            模板存放路径
	 */
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	/**
	 * Get the 模板存放路径.
	 * 
	 * @return 模板存放路径
	 */
	public String getFilePath() {
		return this.filePath;
	}

	@Override
	public String toString() {
		return "InfoTemplete [id=" + id + ", name=" + name + ", picturePath=" + picturePath + ", type=" + type
				+ ", createdAt=" + createdAt + ", filePath=" + filePath + "]";
	}

}
