package com.zyhao.openec.entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Model class of 方案.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity(name="info_plan")
public class InfoPlan implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	@Id
	@GeneratedValue
	private Long id;
	
	/** 方案名称. */
	private String name;

	/** 店铺ID. */
	private Long storeId;

	/** 类型：0-首页1-商品详情. */
	private String type;

	/** 模板ID. */
	private String infoTempleteId;

	/** 生成的文件名称. */
	private String outFileName;

	/** 激活0-不激活 1-激活. */
	private String active;

	/**
	 * Constructor.
	 */
	public InfoPlan() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param id
	 *            主键
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 方案名称.
	 * 
	 * @param name
	 *            方案名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 方案名称.
	 * 
	 * @return 方案名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 店铺ID.
	 * 
	 * @param storeId
	 *            店铺ID
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * Get the 店铺ID.
	 * 
	 * @return 店铺ID
	 */
	public Long getStoreId() {
		return this.storeId;
	}

	/**
	 * Set the 类型：0-首页1-商品详情.
	 * 
	 * @param type
	 *            类型：0-首页1-商品详情
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Get the 类型：0-首页1-商品详情.
	 * 
	 * @return 类型：0-首页1-商品详情
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * Set the 模板ID.
	 * 
	 * @param infoTempleteId
	 *            模板ID
	 */
	public void setInfoTempleteId(String infoTempleteId) {
		this.infoTempleteId = infoTempleteId;
	}

	/**
	 * Get the 模板ID.
	 * 
	 * @return 模板ID
	 */
	public String getInfoTempleteId() {
		return this.infoTempleteId;
	}

	/**
	 * Set the 生成的文件名称.
	 * 
	 * @param outFileName
	 *            生成的文件名称
	 */
	public void setOutFileName(String outFileName) {
		this.outFileName = outFileName;
	}

	/**
	 * Get the 生成的文件名称.
	 * 
	 * @return 生成的文件名称
	 */
	public String getOutFileName() {
		return this.outFileName;
	}

	/**
	 * Set the 激活0-不激活 1-激活.
	 * 
	 * @param active
	 *            激活0-不激活 1-激活
	 */
	public void setActive(String active) {
		this.active = active;
	}

	/**
	 * Get the 激活0-不激活 1-激活.
	 * 
	 * @return 激活0-不激活 1-激活
	 */
	public String getActive() {
		return this.active;
	}

	@Override
	public String toString() {
		return "InfoPlan [id=" + id + ", name=" + name + ", storeId=" + storeId + ", type=" + type + ", infoTempleteId="
				+ infoTempleteId + ", outFileName=" + outFileName + ", active=" + active + "]";
	}

}
